FROM php:8.2-apache

# ติดตั้ง driver MySQL
RUN docker-php-ext-install pdo pdo_mysql

# คัดลอกโค้ด
COPY index.php /var/www/html/

# กำหนดสิทธิ์
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80

CMD ["apache2-foreground"]
