FROM php:8.2-apache

# 1. ติดตั้งไดรเวอร์เชื่อมต่อ MySQL
RUN docker-php-ext-install pdo pdo_mysql

# 2. ปรับแต่งให้อ่าน Port ตามตัวแปรของเซิร์ฟเวอร์
RUN sed -i 's/80/${PORT}/g' /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf

# 3. คัดลอกไฟล์หน้าเว็บ
COPY index.php /var/www/html/

# 4. ตั้งสิทธิ์โฟลเดอร์
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80

# 5. คำสั่งบังคับให้ Apache ทำงานค้างไว้ตลอดเวลา ไม่ให้ Container ดับ
CMD ["apache2-foreground"]
